piVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-node
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nagybalazs89/argo-app-demo.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-node

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true